filter:
    paths: [src/*]
    excluded_paths: [vendor/*, test/*]
before_commands:
    - 'composer install --dev --prefer-source'

build:
  environment:
    postgresql: false
    mysql: false
    redis: false
  tests:
    override:
      - php-scrutinizer-run
      - ./vendor/bin/codecept run
  nodes:
    php80:
      environment:
        php:
          version: 8.0
    php81:
      environment:
        php:
          version: 8.1
