name: CI
on:
  - pull_request

jobs:
  acceptance_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.2', '8.3', '8.4', '8.5' ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl
          ini-values: post_max_size=256M, max_execution_time=180
          coverage: xdebug
          tools: php-cs-fixer, phpunit:${{ matrix.phpunit-versions }}
      - name: Validate composer.json
        run: composer validate
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction --no-suggest
      - name: Codeception
        run: php vendor/bin/codecept run
